server:
  port: 8081  # Port for Product Service

spring:
  application:
    name: product-service

  # datasource:
  #   url: jdbc:h2:mem:productdb
  #   username: sa
  #   password:
  #   driver-class-name: com.h2.Driver
  datasource:
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


  

